"""add global_cbi_stars and company_ratings

Revision ID: 17220f9ec8d6
Revises: dd6cc9679f65
Create Date: 2026-04-07 18:06:54.916386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17220f9ec8d6'
down_revision: Union[str, None] = 'dd6cc9679f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_window_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('global_cbi_stars', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_domain_name'), 'companies', ['domain_name'], unique=False)
    op.create_index(op.f('ix_companies_global_cbi_stars'), 'companies', ['global_cbi_stars'], unique=False)
    op.create_index(op.f('ix_companies_gstin'), 'companies', ['gstin'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_is_verified'), 'companies', ['is_verified'], unique=False)
    op.create_table('credibility_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calculation_window_days', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credibility_config_created_at'), 'credibility_config', ['created_at'], unique=False)
    op.create_index(op.f('ix_credibility_config_id'), 'credibility_config', ['id'], unique=False)
    op.create_index(op.f('ix_credibility_config_last_updated_at'), 'credibility_config', ['last_updated_at'], unique=False)
    op.create_table('po_reminder_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('before_days', sa.JSON(), nullable=True),
    sa.Column('after_due_daily_enabled', sa.Boolean(), nullable=True),
    sa.Column('reminder_subject', sa.String(length=255), nullable=True),
    sa.Column('reminder_body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_reminder_configs_id'), 'po_reminder_configs', ['id'], unique=False)
    op.create_table('sop_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_credibility_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('calculation_window_days', sa.Integer(), nullable=False),
    sa.Column('total_pos', sa.Integer(), nullable=False),
    sa.Column('paid_on_time', sa.Integer(), nullable=False),
    sa.Column('paid_late', sa.Integer(), nullable=False),
    sa.Column('unpaid', sa.Integer(), nullable=False),
    sa.Column('avg_delay_days', sa.Float(), nullable=False),
    sa.Column('max_delay_days', sa.Integer(), nullable=False),
    sa.Column('overdue_count', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_credibility_index_company_id'), 'company_credibility_index', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_credibility_index_grade'), 'company_credibility_index', ['grade'], unique=False)
    op.create_index(op.f('ix_company_credibility_index_id'), 'company_credibility_index', ['id'], unique=False)
    op.create_index(op.f('ix_company_credibility_index_last_calculated_at'), 'company_credibility_index', ['last_calculated_at'], unique=False)
    op.create_index(op.f('ix_company_credibility_index_risk_level'), 'company_credibility_index', ['risk_level'], unique=False)
    op.create_index(op.f('ix_company_credibility_index_score'), 'company_credibility_index', ['score'], unique=False)
    op.create_table('company_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_company_id', sa.String(length=36), nullable=False),
    sa.Column('to_company_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rating_from_to', 'company_ratings', ['from_company_id', 'to_company_id'], unique=True)
    op.create_index(op.f('ix_company_ratings_created_at'), 'company_ratings', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_ratings_from_company_id'), 'company_ratings', ['from_company_id'], unique=False)
    op.create_index(op.f('ix_company_ratings_id'), 'company_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_company_ratings_rating'), 'company_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_company_ratings_to_company_id'), 'company_ratings', ['to_company_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_company_id'), 'invitations', ['company_id'], unique=False)
    op.create_index(op.f('ix_invitations_created_at'), 'invitations', ['created_at'], unique=False)
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('related_po_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_related_po_id'), 'notifications', ['related_po_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('purchase_order_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_audit_logs_action'), 'purchase_order_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_purchase_order_audit_logs_id'), 'purchase_order_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_audit_logs_performed_by_user_id'), 'purchase_order_audit_logs', ['performed_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_audit_logs_purchase_order_id'), 'purchase_order_audit_logs', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_audit_logs_timestamp'), 'purchase_order_audit_logs', ['timestamp'], unique=False)
    op.create_table('scheduled_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_reminders_id'), 'scheduled_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_reminders_purchase_order_id'), 'scheduled_reminders', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_scheduled_reminders_scheduled_at'), 'scheduled_reminders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_reminders_sent_at'), 'scheduled_reminders', ['sent_at'], unique=False)
    op.create_index(op.f('ix_scheduled_reminders_user_id'), 'scheduled_reminders', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.drop_constraint(op.f('payments_plan_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'plans', ['plan_id'], ['id'])
    op.alter_column('plans', 'duration_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.create_index(op.f('ix_plans_duration_type'), 'plans', ['duration_type'], unique=False)
    op.add_column('purchase_orders', sa.Column('company_id', sa.String(length=36), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_number', sa.String(length=100), nullable=False))
    op.add_column('purchase_orders', sa.Column('vendor', sa.String(length=255), nullable=False))
    op.add_column('purchase_orders', sa.Column('gstin', sa.String(length=15), nullable=False))
    op.add_column('purchase_orders', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('purchase_orders', sa.Column('supplier_address', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('invoice_address', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('payment_completed_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('vendor_email', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('vendor_phone', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_notice_sent_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_support_requested_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('payment_window_days', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_po_user_status'), table_name='purchase_orders')
    op.drop_index(op.f('idx_po_vendor_gstin'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_is_archived'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_vendor_gstin'), table_name='purchase_orders')
    op.create_index('idx_po_company_status', 'purchase_orders', ['company_id', 'status'], unique=False)
    op.create_index('idx_po_gstin', 'purchase_orders', ['gstin'], unique=False)
    op.create_index('idx_po_payment', 'purchase_orders', ['payment_completed_at'], unique=False)
    op.create_index(op.f('ix_purchase_orders_archived'), 'purchase_orders', ['archived'], unique=False)
    op.create_index(op.f('ix_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_gstin'), 'purchase_orders', ['gstin'], unique=False)
    op.create_index(op.f('ix_purchase_orders_payment_completed_at'), 'purchase_orders', ['payment_completed_at'], unique=False)
    op.create_foreign_key(None, 'purchase_orders', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase_orders', 'vendor_gstin')
    op.drop_column('purchase_orders', 'number')
    op.drop_column('purchase_orders', 'vendor_name')
    op.drop_column('purchase_orders', 'is_archived')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_constraint(op.f('fk_subscriptions_payment_id'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'payments', ['payment_id'], ['id'])
    op.drop_constraint(op.f('user_settings_user_id_key'), 'user_settings', type_='unique')
    op.add_column('users', sa.Column('company_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('subscription_bypass', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('full_access', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=20), nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('idx_user_gstin_active'), table_name='users')
    op.drop_index(op.f('ix_users_gstin'), table_name='users')
    op.create_index(op.f('ix_users_gstin'), 'users', ['gstin'], unique=False)
    op.create_index('idx_user_company', 'users', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_full_access'), 'users', ['full_access'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_subscription_bypass'), 'users', ['subscription_bypass'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_bypass'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_full_access'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index('idx_user_company', table_name='users')
    op.drop_index(op.f('ix_users_gstin'), table_name='users')
    op.create_index(op.f('ix_users_gstin'), 'users', ['gstin'], unique=True)
    op.create_index(op.f('idx_user_gstin_active'), 'users', ['gstin', 'is_active'], unique=False)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'full_access')
    op.drop_column('users', 'subscription_bypass')
    op.drop_column('users', 'status')
    op.drop_column('users', 'name')
    op.drop_column('users', 'company_id')
    op.create_unique_constraint(op.f('user_settings_user_id_key'), 'user_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_payment_id'), 'subscriptions', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.add_column('purchase_orders', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('vendor_gstin', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_payment_completed_at'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_gstin'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_company_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_archived'), table_name='purchase_orders')
    op.drop_index('idx_po_payment', table_name='purchase_orders')
    op.drop_index('idx_po_gstin', table_name='purchase_orders')
    op.drop_index('idx_po_company_status', table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_vendor_gstin'), 'purchase_orders', ['vendor_gstin'], unique=False)
    op.create_index(op.f('ix_purchase_orders_is_archived'), 'purchase_orders', ['is_archived'], unique=False)
    op.create_index(op.f('idx_po_vendor_gstin'), 'purchase_orders', ['vendor_gstin'], unique=False)
    op.create_index(op.f('idx_po_user_status'), 'purchase_orders', ['user_id', 'status'], unique=False)
    op.drop_column('purchase_orders', 'payment_window_days')
    op.drop_column('purchase_orders', 'legal_support_requested_at')
    op.drop_column('purchase_orders', 'legal_notice_sent_at')
    op.drop_column('purchase_orders', 'vendor_phone')
    op.drop_column('purchase_orders', 'vendor_email')
    op.drop_column('purchase_orders', 'payment_completed_at')
    op.drop_column('purchase_orders', 'invoice_address')
    op.drop_column('purchase_orders', 'delivery_address')
    op.drop_column('purchase_orders', 'supplier_address')
    op.drop_column('purchase_orders', 'archived')
    op.drop_column('purchase_orders', 'gstin')
    op.drop_column('purchase_orders', 'vendor')
    op.drop_column('purchase_orders', 'po_number')
    op.drop_column('purchase_orders', 'company_id')
    op.drop_index(op.f('ix_plans_duration_type'), table_name='plans')
    op.alter_column('plans', 'duration_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_plan_id_fkey'), 'payments', 'plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_scheduled_reminders_user_id'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_sent_at'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_scheduled_at'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_purchase_order_id'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_id'), table_name='scheduled_reminders')
    op.drop_table('scheduled_reminders')
    op.drop_index(op.f('ix_purchase_order_audit_logs_timestamp'), table_name='purchase_order_audit_logs')
    op.drop_index(op.f('ix_purchase_order_audit_logs_purchase_order_id'), table_name='purchase_order_audit_logs')
    op.drop_index(op.f('ix_purchase_order_audit_logs_performed_by_user_id'), table_name='purchase_order_audit_logs')
    op.drop_index(op.f('ix_purchase_order_audit_logs_id'), table_name='purchase_order_audit_logs')
    op.drop_index(op.f('ix_purchase_order_audit_logs_action'), table_name='purchase_order_audit_logs')
    op.drop_table('purchase_order_audit_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_po_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_expires_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_created_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_company_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_company_ratings_to_company_id'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_rating'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_id'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_from_company_id'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_created_at'), table_name='company_ratings')
    op.drop_index('idx_rating_from_to', table_name='company_ratings')
    op.drop_table('company_ratings')
    op.drop_index(op.f('ix_company_credibility_index_score'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_risk_level'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_last_calculated_at'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_id'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_grade'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_company_id'), table_name='company_credibility_index')
    op.drop_table('company_credibility_index')
    op.drop_table('sop_documents')
    op.drop_index(op.f('ix_po_reminder_configs_id'), table_name='po_reminder_configs')
    op.drop_table('po_reminder_configs')
    op.drop_index(op.f('ix_credibility_config_last_updated_at'), table_name='credibility_config')
    op.drop_index(op.f('ix_credibility_config_id'), table_name='credibility_config')
    op.drop_index(op.f('ix_credibility_config_created_at'), table_name='credibility_config')
    op.drop_table('credibility_config')
    op.drop_index(op.f('ix_companies_is_verified'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_gstin'), table_name='companies')
    op.drop_index(op.f('ix_companies_global_cbi_stars'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
