"""add is_archived to purchase orders

Revision ID: 3d2565c409c0
Revises: c80537e2d8c0
Create Date: 2026-01-04 21:31:29.190897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2565c409c0'
down_revision: Union[str, None] = 'c80537e2d8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_is_archived'), 'purchase_orders', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_orders_is_archived'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'is_archived')
    # ### end Alembic commands ###
