"""add sales invoice tables

Revision ID: 6f2cd4edd879
Revises: e1c033d71428
Create Date: 2026-07-29 22:41:05.191545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f2cd4edd879'
down_revision: Union[str, None] = 'e1c033d71428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _safe_create_index(*args, **kwargs):
    """Create an index, silently skipping it if it already exists.

    This migration duplicates a very large number of indexes that were
    already created by earlier migrations in the chain (an artifact of
    this file having been autogenerated against a hand-patched database).
    Rather than manually removing every duplicate one at a time, each
    create_index call is run inside its own SAVEPOINT so a "relation
    already exists" error only rolls back that one statement instead of
    aborting the whole migration transaction.
    """
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.create_index(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def _safe_create_foreign_key(*args, **kwargs):
    """Same idea as _safe_create_index, but for FK constraints — unnamed
    FKs get a deterministic auto-generated name from Postgres, so a
    duplicate call collides just like a duplicate index would."""
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.create_foreign_key(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def _safe_create_unique_constraint(*args, **kwargs):
    """Same idea as _safe_create_index, but for unique constraints."""
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.create_unique_constraint(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def _safe_add_column(*args, **kwargs):
    """Same idea as _safe_create_index, but for columns. A number of
    tables in this migration were originally created (in earlier
    migrations) already including columns this file tries to add again —
    this makes every add_column call idempotent instead of tracking down
    each conflicting column one at a time."""
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.add_column(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def _safe_drop_constraint(*args, **kwargs):
    """This migration also has the opposite problem in places: it drops
    constraints/columns/indexes/tables that were never actually created
    (an artifact of being autogenerated against a database that had
    drifted from the real migration history). Skip silently if the
    target doesn't exist instead of aborting the whole migration."""
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.drop_constraint(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def _safe_drop_column(*args, **kwargs):
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.drop_column(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def _safe_drop_index(*args, **kwargs):
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.drop_index(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def _safe_drop_table(*args, **kwargs):
    bind = op.get_bind()
    nested = bind.begin_nested()
    try:
        op.drop_table(*args, **kwargs)
        nested.commit()
    except Exception:
        nested.rollback()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: 'app_settings' and 'credibility_config' are already created by
    # 17220f9ec8d6, which this migration depends on via the merged chain.
    # The duplicate create_table calls here were removed to avoid
    # "relation already exists" errors.
    # NOTE: 'company_ratings', 'business_profiles', and 'credit_reports' were
    # also already created earlier in the migration chain (17220f9ec8d6 and
    # 0ae42e959edb respectively). Removed for the same reason.
    op.create_table('sales_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('payment_due_date', sa.DateTime(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.DateTime(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('customer_gstin', sa.String(length=15), nullable=True),
    sa.Column('customer_pan', sa.String(length=10), nullable=True),
    sa.Column('ship_to_name', sa.String(length=255), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('lut_arn', sa.String(length=50), nullable=True),
    sa.Column('lut_filing_date', sa.DateTime(), nullable=True),
    sa.Column('msme_no', sa.String(length=50), nullable=True),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('is_sez_supply', sa.Boolean(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('balance_due', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index('idx_sales_invoice_company_status', 'sales_invoices', ['company_id', 'status'], unique=False)
    _safe_create_index('idx_sales_invoice_due_date', 'sales_invoices', ['payment_due_date'], unique=False)
    _safe_create_index('idx_sales_invoice_number', 'sales_invoices', ['invoice_number'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_archived'), 'sales_invoices', ['archived'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_company_id'), 'sales_invoices', ['company_id'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_country'), 'sales_invoices', ['country'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_created_at'), 'sales_invoices', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_customer_gstin'), 'sales_invoices', ['customer_gstin'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_id'), 'sales_invoices', ['id'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_invoice_date'), 'sales_invoices', ['invoice_date'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_invoice_number'), 'sales_invoices', ['invoice_number'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_payment_due_date'), 'sales_invoices', ['payment_due_date'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_po_number'), 'sales_invoices', ['po_number'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_status'), 'sales_invoices', ['status'], unique=False)
    _safe_create_index(op.f('ix_sales_invoices_user_id'), 'sales_invoices', ['user_id'], unique=False)
    # NOTE: 'user_settings' (a1b2c3d4e5f6), 'credibility_reviews' and
    # 'credibility_review_stages' (ec42f3e94788), and
    # 'purchase_order_audit_logs' (17220f9ec8d6) are already created earlier
    # in the migration chain. Duplicate create_table calls removed here.
    op.create_table('sales_invoice_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sales_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_sales_invoice_audit_logs_action'), 'sales_invoice_audit_logs', ['action'], unique=False)
    _safe_create_index(op.f('ix_sales_invoice_audit_logs_id'), 'sales_invoice_audit_logs', ['id'], unique=False)
    _safe_create_index(op.f('ix_sales_invoice_audit_logs_performed_by_user_id'), 'sales_invoice_audit_logs', ['performed_by_user_id'], unique=False)
    _safe_create_index(op.f('ix_sales_invoice_audit_logs_sales_invoice_id'), 'sales_invoice_audit_logs', ['sales_invoice_id'], unique=False)
    _safe_create_index(op.f('ix_sales_invoice_audit_logs_timestamp'), 'sales_invoice_audit_logs', ['timestamp'], unique=False)
    op.create_table('sales_invoice_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('igst_percent', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_sales_invoice_items_id'), 'sales_invoice_items', ['id'], unique=False)
    _safe_create_index(op.f('ix_sales_invoice_items_invoice_id'), 'sales_invoice_items', ['invoice_id'], unique=False)
    # NOTE: 'credibility_review_stages' (and its enum types) already
    # created earlier by ec42f3e94788. Duplicate create_table removed here.
    # NOTE: 'role_settings', 'subscription_requests', 'system_settings', and
    # 'workflow_items' are only ever created later in this same migration
    # (further down in upgrade()) — they don't exist yet at this point on a
    # fresh database, so the DROP TABLE calls that used to be here (leftover
    # from an autogenerated diff against a hand-patched dev database) were
    # removed to avoid "table does not exist" errors.
    # NOTE: 'contact_email', 'contact_phone', 'notes', 'updated_at' and all
    # the indexes/FK below were already created by 126b146b34b0's original
    # create_table('appointments', ...) call. Removed duplicates; the
    # alter_column calls are harmless no-ops if already applied, so kept.
    op.alter_column('appointments', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('appointments', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('appointments', 'appointment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('appointments', 'purpose',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_add_column('audit_logs', sa.Column('user_email', sa.String(length=255), nullable=True))
    _safe_add_column('audit_logs', sa.Column('user_name', sa.String(length=255), nullable=True))
    _safe_add_column('audit_logs', sa.Column('po_number', sa.String(length=100), nullable=True))
    _safe_add_column('audit_logs', sa.Column('vendor_name', sa.String(length=255), nullable=True))
    _safe_add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_audit_log_action', 'audit_logs', ['action', 'created_at'], unique=False)
    _safe_create_index('idx_audit_log_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    _safe_create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    _safe_create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    _safe_create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    _safe_create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    _safe_create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('business_requests', sa.Column('user_email', sa.String(length=255), nullable=True))
    _safe_add_column('business_requests', sa.Column('company_name', sa.String(length=255), nullable=False))
    _safe_add_column('business_requests', sa.Column('legal_notes', sa.Text(), nullable=True))
    op.alter_column('business_requests', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('business_requests', 'gstin',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('business_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('business_requests', 'risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('business_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index(op.f('ix_business_requests_created_at'), 'business_requests', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_business_requests_gstin'), 'business_requests', ['gstin'], unique=False)
    _safe_create_index(op.f('ix_business_requests_id'), 'business_requests', ['id'], unique=False)
    _safe_create_index(op.f('ix_business_requests_status'), 'business_requests', ['status'], unique=False)
    _safe_create_index(op.f('ix_business_requests_user_email'), 'business_requests', ['user_email'], unique=False)
    _safe_create_index(op.f('ix_business_requests_user_id'), 'business_requests', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'business_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _safe_create_foreign_key(None, 'business_requests', 'users', ['analyzed_by'], ['id'])
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_drop_constraint(op.f('companies_gstin_key'), 'companies', type_='unique')
    _safe_create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_companies_domain_name'), 'companies', ['domain_name'], unique=False)
    _safe_create_index(op.f('ix_companies_global_cbi_stars'), 'companies', ['global_cbi_stars'], unique=False)
    _safe_create_index(op.f('ix_companies_gstin'), 'companies', ['gstin'], unique=True)
    _safe_create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    _safe_create_index(op.f('ix_companies_is_verified'), 'companies', ['is_verified'], unique=False)
    _safe_add_column('company_credibility_index', sa.Column('ai_summary', sa.Text(), nullable=True))
    _safe_add_column('company_credibility_index', sa.Column('calculation_window_days', sa.Integer(), nullable=False))
    _safe_add_column('company_credibility_index', sa.Column('unpaid', sa.Integer(), nullable=False))
    _safe_add_column('company_credibility_index', sa.Column('max_delay_days', sa.Integer(), nullable=False))
    _safe_add_column('company_credibility_index', sa.Column('overdue_count', sa.Integer(), nullable=False))
    _safe_add_column('company_credibility_index', sa.Column('last_calculated_at', sa.DateTime(), nullable=True))
    op.alter_column('company_credibility_index', 'company_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('company_credibility_index', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'grade',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('company_credibility_index', 'risk_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('company_credibility_index', 'total_pos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'paid_on_time',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'paid_late',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'avg_delay_days',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    _safe_create_index(op.f('ix_company_credibility_index_company_id'), 'company_credibility_index', ['company_id'], unique=True)
    _safe_create_index(op.f('ix_company_credibility_index_grade'), 'company_credibility_index', ['grade'], unique=False)
    _safe_create_index(op.f('ix_company_credibility_index_id'), 'company_credibility_index', ['id'], unique=False)
    _safe_create_index(op.f('ix_company_credibility_index_last_calculated_at'), 'company_credibility_index', ['last_calculated_at'], unique=False)
    _safe_create_index(op.f('ix_company_credibility_index_risk_level'), 'company_credibility_index', ['risk_level'], unique=False)
    _safe_create_index(op.f('ix_company_credibility_index_score'), 'company_credibility_index', ['score'], unique=False)
    _safe_create_foreign_key(None, 'company_credibility_index', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    _safe_drop_column('company_credibility_index', 'updated_at')
    _safe_drop_column('company_credibility_index', 'created_at')
    op.alter_column('company_user_edit_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index(op.f('ix_company_user_edit_requests_created_at'), 'company_user_edit_requests', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_company_user_edit_requests_entity_id'), 'company_user_edit_requests', ['entity_id'], unique=False)
    _safe_create_index(op.f('ix_company_user_edit_requests_entity_type'), 'company_user_edit_requests', ['entity_type'], unique=False)
    _safe_create_index(op.f('ix_company_user_edit_requests_id'), 'company_user_edit_requests', ['id'], unique=False)
    _safe_create_index(op.f('ix_company_user_edit_requests_status'), 'company_user_edit_requests', ['status'], unique=False)
    _safe_add_column('defaulter_cases', sa.Column('user_id', sa.String(length=36), nullable=False))
    _safe_add_column('defaulter_cases', sa.Column('business_name', sa.String(length=255), nullable=False))
    # NOTE: 'pan', 'verified_by', 'verification_date' already added by 7060e0366f6a — removed duplicates
    _safe_add_column('defaulter_cases', sa.Column('due_date', sa.DateTime(), nullable=False))
    _safe_add_column('defaulter_cases', sa.Column('notes', sa.Text(), nullable=True))
    _safe_add_column('defaulter_cases', sa.Column('documents_drive_folder', sa.String(length=500), nullable=True))
    _safe_add_column('defaulter_cases', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('defaulter_cases', 'invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('defaulter_cases', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('defaulter_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_defaulter_approval_date', 'defaulter_cases', ['approval_status', 'created_at'], unique=False)
    _safe_create_index('idx_defaulter_business_gstin', 'defaulter_cases', ['business_gstin'], unique=False)
    _safe_create_index('idx_defaulter_user_status', 'defaulter_cases', ['user_id', 'approval_status'], unique=False)
    _safe_create_index(op.f('ix_defaulter_cases_approval_status'), 'defaulter_cases', ['approval_status'], unique=False)
    _safe_create_index(op.f('ix_defaulter_cases_business_gstin'), 'defaulter_cases', ['business_gstin'], unique=False)
    _safe_create_index(op.f('ix_defaulter_cases_created_at'), 'defaulter_cases', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_defaulter_cases_due_date'), 'defaulter_cases', ['due_date'], unique=False)
    _safe_create_index(op.f('ix_defaulter_cases_id'), 'defaulter_cases', ['id'], unique=False)
    # NOTE: 'ix_defaulter_cases_pan' already created by 7060e0366f6a — removed duplicate
    _safe_create_index(op.f('ix_defaulter_cases_user_id'), 'defaulter_cases', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'defaulter_cases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('global_credibility_index', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('global_credibility_index', 'company_registration_no',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'partner_trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('global_credibility_index', 'ai_credit_risk_verdict',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW_RISK', 'MEDIUM_RISK', 'HIGH_RISK', 'NOT_RATED', name='aicreditriskverdict'),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'credibility_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CREDIBILITY_VERIFIED', 'STANDARD', name='credibilitystatus'),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'legal_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CLEAN', 'MINOR_DISPUTES', 'ACTIVE_LITIGATION', 'BLACKLISTED', name='legalstatus'),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'operational_reliability',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', name='operationalreliability'),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index(op.f('ix_global_credibility_index_approved_by_master_admin_id'), 'global_credibility_index', ['approved_by_master_admin_id'], unique=False)
    _safe_create_index(op.f('ix_global_credibility_index_company_id'), 'global_credibility_index', ['company_id'], unique=True)
    _safe_create_index(op.f('ix_global_credibility_index_company_name'), 'global_credibility_index', ['company_name'], unique=False)
    _safe_create_index(op.f('ix_global_credibility_index_company_registration_no'), 'global_credibility_index', ['company_registration_no'], unique=False)
    _safe_create_index(op.f('ix_global_credibility_index_created_at'), 'global_credibility_index', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_global_credibility_index_credibility_review_id'), 'global_credibility_index', ['credibility_review_id'], unique=False)
    _safe_create_index(op.f('ix_global_credibility_index_id'), 'global_credibility_index', ['id'], unique=False)
    _safe_create_foreign_key(None, 'global_credibility_index', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    _safe_create_foreign_key(None, 'global_credibility_index', 'credibility_reviews', ['credibility_review_id'], ['id'], ondelete='CASCADE')
    _safe_create_foreign_key(None, 'global_credibility_index', 'users', ['approved_by_master_admin_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invitations', 'company_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('invitations', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invitations', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
    op.alter_column('invitations', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('invitations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index(op.f('ix_invitations_company_id'), 'invitations', ['company_id'], unique=False)
    _safe_create_index(op.f('ix_invitations_created_at'), 'invitations', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    _safe_create_index(op.f('ix_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    _safe_create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    _safe_create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    _safe_create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    _safe_create_foreign_key(None, 'invitations', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('invoices', sa.Column('user_id', sa.String(length=36), nullable=False))
    _safe_add_column('invoices', sa.Column('counterparty_name', sa.String(length=255), nullable=False))
    _safe_add_column('invoices', sa.Column('counterparty_pan', sa.String(length=10), nullable=True))
    _safe_add_column('invoices', sa.Column('invoice_number', sa.String(length=100), nullable=False))
    _safe_add_column('invoices', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    _safe_add_column('invoices', sa.Column('reminder_frequency_days', sa.Integer(), nullable=True))
    _safe_add_column('invoices', sa.Column('reminder_next_at', sa.DateTime(), nullable=True))
    _safe_add_column('invoices', sa.Column('last_follow_up_at', sa.DateTime(), nullable=True))
    _safe_add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    _safe_add_column('invoices', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_invoice_counterparty', 'invoices', ['counterparty_gstin', 'counterparty_pan'], unique=False)
    _safe_create_index('idx_invoice_user_status', 'invoices', ['user_id', 'status'], unique=False)
    _safe_create_index(op.f('ix_invoices_counterparty_gstin'), 'invoices', ['counterparty_gstin'], unique=False)
    _safe_create_index(op.f('ix_invoices_counterparty_pan'), 'invoices', ['counterparty_pan'], unique=False)
    _safe_create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    _safe_create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    _safe_create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    _safe_create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    _safe_create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    _safe_create_index(op.f('ix_notifications_related_po_id'), 'notifications', ['related_po_id'], unique=False)
    _safe_create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    _safe_create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    _safe_create_foreign_key(None, 'notifications', 'purchase_orders', ['related_po_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('payments', sa.Column('currency', sa.String(length=10), nullable=False))
    _safe_add_column('payments', sa.Column('payment_provider', sa.String(length=50), nullable=True))
    _safe_add_column('payments', sa.Column('reference_id', sa.String(length=255), nullable=False))
    _safe_add_column('payments', sa.Column('gateway_order_id', sa.String(length=255), nullable=True))
    _safe_add_column('payments', sa.Column('gateway_payment_id', sa.String(length=255), nullable=True))
    _safe_add_column('payments', sa.Column('failure_reason', sa.Text(), nullable=True))
    _safe_add_column('payments', sa.Column('payment_metadata', sa.JSON(), nullable=True))
    # NOTE: 'payment_proof_filename' already added by e1c033d71428 — removed duplicate
    _safe_add_column('payments', sa.Column('initiated_at', sa.DateTime(), nullable=False))
    _safe_add_column('payments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    _safe_add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('payments', 'plan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_payment_status_created', 'payments', ['status', 'created_at'], unique=False)
    _safe_create_index('idx_payment_user_status', 'payments', ['user_id', 'status'], unique=False)
    _safe_create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    _safe_create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    _safe_create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    _safe_create_index(op.f('ix_payments_reference_id'), 'payments', ['reference_id'], unique=True)
    _safe_create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    _safe_create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    _safe_create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'payments', 'plans', ['plan_id'], ['id'])
    _safe_create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('plans', sa.Column('display_name', sa.String(length=100), nullable=False))
    _safe_add_column('plans', sa.Column('description', sa.Text(), nullable=True))
    # NOTE: 'duration_type' already added by a1b2c3d4e5f6 — removed duplicate
    _safe_add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=True))
    _safe_add_column('plans', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('plans', 'validity_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'follow_up_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'legal_assistance_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_plan_active', 'plans', ['is_active'], unique=False)
    # NOTE: 'idx_plan_duration' already created by a1b2c3d4e5f6 — removed duplicate
    _safe_create_index(op.f('ix_plans_duration_type'), 'plans', ['duration_type'], unique=False)
    _safe_create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    _safe_create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    _safe_create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    _safe_add_column('po_reminder_configs', sa.Column('reminder_body', sa.Text(), nullable=True))
    _safe_create_index(op.f('ix_po_reminder_configs_id'), 'po_reminder_configs', ['id'], unique=False)
    _safe_drop_column('po_reminder_configs', 'purchase_order_id')
    _safe_drop_column('po_reminder_configs', 'created_at')
    op.alter_column('purchase_orders', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('purchase_orders', 'vendor',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchase_orders', 'gstin',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('purchase_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_po_company_status', 'purchase_orders', ['company_id', 'status'], unique=False)
    _safe_create_index('idx_po_gstin', 'purchase_orders', ['gstin'], unique=False)
    _safe_create_index('idx_po_payment', 'purchase_orders', ['payment_completed_at'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_archived'), 'purchase_orders', ['archived'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_created_at'), 'purchase_orders', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_due_date'), 'purchase_orders', ['due_date'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_gstin'), 'purchase_orders', ['gstin'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_payment_completed_at'), 'purchase_orders', ['payment_completed_at'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    _safe_create_index(op.f('ix_purchase_orders_user_id'), 'purchase_orders', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'purchase_orders', 'users', ['approved_by'], ['id'])
    _safe_create_foreign_key(None, 'purchase_orders', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    _safe_create_foreign_key(None, 'purchase_orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('scheduled_reminders', 'purchase_order_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('scheduled_reminders', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('scheduled_reminders', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('scheduled_reminders', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('scheduled_reminders', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('scheduled_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index(op.f('ix_scheduled_reminders_id'), 'scheduled_reminders', ['id'], unique=False)
    _safe_create_index(op.f('ix_scheduled_reminders_purchase_order_id'), 'scheduled_reminders', ['purchase_order_id'], unique=False)
    _safe_create_index(op.f('ix_scheduled_reminders_scheduled_at'), 'scheduled_reminders', ['scheduled_at'], unique=False)
    _safe_create_index(op.f('ix_scheduled_reminders_sent_at'), 'scheduled_reminders', ['sent_at'], unique=False)
    _safe_create_index(op.f('ix_scheduled_reminders_user_id'), 'scheduled_reminders', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'scheduled_reminders', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='CASCADE')
    _safe_create_foreign_key(None, 'scheduled_reminders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('settlements', sa.Column('notes', sa.Text(), nullable=True))
    _safe_add_column('settlements', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('settlements', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('settlements', 'case_reference',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_settlement_user_status', 'settlements', ['user_id', 'status'], unique=False)
    _safe_create_index(op.f('ix_settlements_created_at'), 'settlements', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    _safe_create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    _safe_create_index(op.f('ix_settlements_user_id'), 'settlements', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'settlements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('sop_documents', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.alter_column('sop_documents', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sop_documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    _safe_create_index(op.f('ix_sop_documents_id'), 'sop_documents', ['id'], unique=False)
    _safe_create_index(op.f('ix_sop_documents_uploaded_at'), 'sop_documents', ['uploaded_at'], unique=False)
    _safe_drop_column('sop_documents', 'created_at')
    _safe_add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # NOTE: 'payment_id' (a1b2c3d4e5f6) and 'payment_proof_url'/'processed_by'
    # (948c15643e27) already added earlier in the chain — removed duplicates
    _safe_add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    _safe_create_index('idx_subscription_user_active', 'subscriptions', ['user_id', 'is_active'], unique=False)
    _safe_create_index(op.f('ix_subscriptions_expiry_date'), 'subscriptions', ['expiry_date'], unique=False)
    _safe_create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    _safe_create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    # NOTE: 'ix_subscriptions_payment_id' already created by a1b2c3d4e5f6 — removed duplicate
    _safe_create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    _safe_create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    _safe_create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'subscriptions', 'users', ['approved_by'], ['id'])
    _safe_create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # NOTE: FK on 'processed_by' already created by 948c15643e27 — removed duplicate
    _safe_create_foreign_key(None, 'subscriptions', 'users', ['verified_by'], ['id'])
    _safe_create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
    # NOTE: FK on 'payment_id' already created by a1b2c3d4e5f6 — removed duplicate
    _safe_add_column('support_requests', sa.Column('user_name', sa.String(length=255), nullable=True))
    _safe_add_column('support_requests', sa.Column('user_email', sa.String(length=255), nullable=False))
    _safe_add_column('support_requests', sa.Column('company_name', sa.String(length=255), nullable=True))
    _safe_add_column('support_requests', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.alter_column('support_requests', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('support_requests', 'request_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('support_requests', 'request_details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('support_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('support_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index(op.f('ix_support_requests_created_at'), 'support_requests', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_support_requests_id'), 'support_requests', ['id'], unique=False)
    _safe_create_index(op.f('ix_support_requests_request_type'), 'support_requests', ['request_type'], unique=False)
    _safe_create_index(op.f('ix_support_requests_status'), 'support_requests', ['status'], unique=False)
    _safe_create_index(op.f('ix_support_requests_user_email'), 'support_requests', ['user_email'], unique=False)
    _safe_create_index(op.f('ix_support_requests_user_id'), 'support_requests', ['user_id'], unique=False)
    _safe_create_foreign_key(None, 'support_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _safe_create_foreign_key(None, 'support_requests', 'users', ['resolved_by'], ['id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'subscription_bypass',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'full_access',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'INACTIVE'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    _safe_create_index('idx_user_company', 'users', ['company_id', 'status'], unique=False)
    _safe_create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    _safe_create_index('idx_user_role', 'users', ['role'], unique=False)
    _safe_create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    _safe_create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    _safe_create_index(op.f('ix_users_full_access'), 'users', ['full_access'], unique=False)
    _safe_create_index(op.f('ix_users_gstin'), 'users', ['gstin'], unique=False)
    _safe_create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    _safe_create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    _safe_create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    _safe_create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    _safe_create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    _safe_create_index(op.f('ix_users_subscription_bypass'), 'users', ['subscription_bypass'], unique=False)
    _safe_create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    _safe_create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    _safe_create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('wallet_transactions', sa.Column('reference_id', sa.String(length=36), nullable=True))
    _safe_add_column('wallet_transactions', sa.Column('description', sa.String(length=255), nullable=True))
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('wallet_transactions', 'trans_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wallet_transactions', 'reference_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    _safe_create_index('idx_wallet_trans_wallet_date', 'wallet_transactions', ['wallet_id', 'created_at'], unique=False)
    _safe_create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    _safe_create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    _safe_create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    _safe_create_foreign_key(None, 'wallet_transactions', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    _safe_add_column('wallets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('wallets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    _safe_drop_constraint(op.f('wallets_user_id_key'), 'wallets', type_='unique')
    _safe_create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    _safe_create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    _safe_create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _safe_drop_column('wallets', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.create_unique_constraint(op.f('wallets_user_id_key'), 'wallets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('wallets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('wallets', 'updated_at')
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.drop_index('idx_wallet_trans_wallet_date', table_name='wallet_transactions')
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('wallet_transactions', 'reference_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('wallet_transactions', 'trans_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('wallet_transactions', 'description')
    op.drop_column('wallet_transactions', 'reference_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_bypass'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_gstin'), table_name='users')
    op.drop_index(op.f('ix_users_full_access'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_company', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'INACTIVE'::character varying"))
    op.alter_column('users', 'full_access',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'subscription_bypass',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'support_requests', type_='foreignkey')
    op.drop_constraint(None, 'support_requests', type_='foreignkey')
    op.drop_index(op.f('ix_support_requests_user_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_user_email'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_status'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_request_type'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_created_at'), table_name='support_requests')
    op.alter_column('support_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_requests', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('support_requests', 'request_details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('support_requests', 'request_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('support_requests', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('support_requests', 'resolved_at')
    op.drop_column('support_requests', 'company_name')
    op.drop_column('support_requests', 'user_email')
    op.drop_column('support_requests', 'user_name')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    # NOTE: 'ix_subscriptions_payment_id' owned by a1b2c3d4e5f6 — not dropped here
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expiry_date'), table_name='subscriptions')
    op.drop_index('idx_subscription_user_active', table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('subscriptions', 'updated_at')
    # NOTE: 'processed_by', 'payment_proof_url' (948c15643e27) and
    # 'payment_id' (a1b2c3d4e5f6) owned by earlier migrations — not dropped here
    op.drop_column('subscriptions', 'is_active')
    op.add_column('sop_documents', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sop_documents_uploaded_at'), table_name='sop_documents')
    op.drop_index(op.f('ix_sop_documents_id'), table_name='sop_documents')
    op.alter_column('sop_documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sop_documents', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('sop_documents', 'uploaded_at')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_index(op.f('ix_settlements_user_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_created_at'), table_name='settlements')
    op.drop_index('idx_settlement_user_status', table_name='settlements')
    op.alter_column('settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('settlements', 'case_reference',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('settlements', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('settlements', 'updated_at')
    op.drop_column('settlements', 'notes')
    op.drop_constraint(None, 'scheduled_reminders', type_='foreignkey')
    op.drop_constraint(None, 'scheduled_reminders', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_reminders_user_id'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_sent_at'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_scheduled_at'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_purchase_order_id'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_id'), table_name='scheduled_reminders')
    op.alter_column('scheduled_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_reminders', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('scheduled_reminders', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('scheduled_reminders', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('scheduled_reminders', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('scheduled_reminders', 'purchase_order_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_user_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_payment_completed_at'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_gstin'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_due_date'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_at'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_company_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_archived'), table_name='purchase_orders')
    op.drop_index('idx_po_payment', table_name='purchase_orders')
    op.drop_index('idx_po_gstin', table_name='purchase_orders')
    op.drop_index('idx_po_company_status', table_name='purchase_orders')
    op.alter_column('purchase_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_orders', 'gstin',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('purchase_orders', 'vendor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_orders', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('po_reminder_configs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('po_reminder_configs', sa.Column('purchase_order_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_po_reminder_configs_id'), table_name='po_reminder_configs')
    op.drop_column('po_reminder_configs', 'reminder_body')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_duration_type'), table_name='plans')
    # NOTE: 'idx_plan_duration' owned by a1b2c3d4e5f6 — not dropped here
    op.drop_index('idx_plan_active', table_name='plans')
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'legal_assistance_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'follow_up_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'validity_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('plans', 'updated_at')
    op.drop_column('plans', 'is_active')
    # NOTE: 'duration_type' owned by a1b2c3d4e5f6 — not dropped here
    op.drop_column('plans', 'description')
    op.drop_column('plans', 'display_name')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index('idx_payment_user_status', table_name='payments')
    op.drop_index('idx_payment_status_created', table_name='payments')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payments', 'plan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'completed_at')
    op.drop_column('payments', 'initiated_at')
    # NOTE: 'payment_proof_filename' owned by e1c033d71428 — not dropped here
    op.drop_column('payments', 'payment_metadata')
    op.drop_column('payments', 'failure_reason')
    op.drop_column('payments', 'gateway_payment_id')
    op.drop_column('payments', 'gateway_order_id')
    op.drop_column('payments', 'reference_id')
    op.drop_column('payments', 'payment_provider')
    op.drop_column('payments', 'currency')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_po_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_counterparty_pan'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_counterparty_gstin'), table_name='invoices')
    op.drop_index('idx_invoice_user_status', table_name='invoices')
    op.drop_index('idx_invoice_counterparty', table_name='invoices')
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'last_follow_up_at')
    op.drop_column('invoices', 'reminder_next_at')
    op.drop_column('invoices', 'reminder_frequency_days')
    op.drop_column('invoices', 'acknowledged_at')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'counterparty_pan')
    op.drop_column('invoices', 'counterparty_name')
    op.drop_column('invoices', 'user_id')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_expires_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_created_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_company_id'), table_name='invitations')
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invitations', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invitations', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('invitations', 'role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('invitations', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('invitations', 'company_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'global_credibility_index', type_='foreignkey')
    op.drop_constraint(None, 'global_credibility_index', type_='foreignkey')
    op.drop_constraint(None, 'global_credibility_index', type_='foreignkey')
    op.drop_index(op.f('ix_global_credibility_index_id'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_credibility_review_id'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_created_at'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_company_registration_no'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_company_name'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_company_id'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_approved_by_master_admin_id'), table_name='global_credibility_index')
    op.alter_column('global_credibility_index', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_credibility_index', 'operational_reliability',
               existing_type=sa.Enum('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', name='operationalreliability'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'legal_status',
               existing_type=sa.Enum('CLEAN', 'MINOR_DISPUTES', 'ACTIVE_LITIGATION', 'BLACKLISTED', name='legalstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'credibility_status',
               existing_type=sa.Enum('CREDIBILITY_VERIFIED', 'STANDARD', name='credibilitystatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'ai_credit_risk_verdict',
               existing_type=sa.Enum('LOW_RISK', 'MEDIUM_RISK', 'HIGH_RISK', 'NOT_RATED', name='aicreditriskverdict'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'partner_trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('global_credibility_index', 'company_registration_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('global_credibility_index', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'defaulter_cases', type_='foreignkey')
    op.drop_index(op.f('ix_defaulter_cases_user_id'), table_name='defaulter_cases')
    # NOTE: 'ix_defaulter_cases_pan' owned by 7060e0366f6a — not dropped here
    op.drop_index(op.f('ix_defaulter_cases_id'), table_name='defaulter_cases')
    op.drop_index(op.f('ix_defaulter_cases_due_date'), table_name='defaulter_cases')
    op.drop_index(op.f('ix_defaulter_cases_created_at'), table_name='defaulter_cases')
    op.drop_index(op.f('ix_defaulter_cases_business_gstin'), table_name='defaulter_cases')
    op.drop_index(op.f('ix_defaulter_cases_approval_status'), table_name='defaulter_cases')
    op.drop_index('idx_defaulter_user_status', table_name='defaulter_cases')
    op.drop_index('idx_defaulter_business_gstin', table_name='defaulter_cases')
    op.drop_index('idx_defaulter_approval_date', table_name='defaulter_cases')
    op.alter_column('defaulter_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('defaulter_cases', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('defaulter_cases', 'invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('defaulter_cases', 'updated_at')
    op.drop_column('defaulter_cases', 'documents_drive_folder')
    op.drop_column('defaulter_cases', 'notes')
    # NOTE: 'verification_date', 'verified_by', 'pan' owned by 7060e0366f6a — not dropped here
    op.drop_column('defaulter_cases', 'due_date')
    op.drop_column('defaulter_cases', 'business_name')
    op.drop_column('defaulter_cases', 'user_id')
    op.drop_index(op.f('ix_company_user_edit_requests_status'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_id'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_entity_type'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_entity_id'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_created_at'), table_name='company_user_edit_requests')
    op.alter_column('company_user_edit_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('company_credibility_index', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('company_credibility_index', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_credibility_index', type_='foreignkey')
    op.drop_index(op.f('ix_company_credibility_index_score'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_risk_level'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_last_calculated_at'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_id'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_grade'), table_name='company_credibility_index')
    op.drop_index(op.f('ix_company_credibility_index_company_id'), table_name='company_credibility_index')
    op.alter_column('company_credibility_index', 'avg_delay_days',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'paid_late',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'paid_on_time',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'total_pos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'risk_level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('company_credibility_index', 'grade',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('company_credibility_index', 'score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('company_credibility_index', 'company_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('company_credibility_index', 'last_calculated_at')
    op.drop_column('company_credibility_index', 'overdue_count')
    op.drop_column('company_credibility_index', 'max_delay_days')
    op.drop_column('company_credibility_index', 'unpaid')
    op.drop_column('company_credibility_index', 'calculation_window_days')
    op.drop_column('company_credibility_index', 'ai_summary')
    op.drop_index(op.f('ix_companies_is_verified'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_gstin'), table_name='companies')
    op.drop_index(op.f('ix_companies_global_cbi_stars'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.create_unique_constraint(op.f('companies_gstin_key'), 'companies', ['gstin'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'business_requests', type_='foreignkey')
    op.drop_constraint(None, 'business_requests', type_='foreignkey')
    op.drop_index(op.f('ix_business_requests_user_id'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_user_email'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_status'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_id'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_gstin'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_created_at'), table_name='business_requests')
    op.alter_column('business_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('business_requests', 'risk_score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('business_requests', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('business_requests', 'gstin',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('business_requests', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('business_requests', 'legal_notes')
    op.drop_column('business_requests', 'company_name')
    op.drop_column('business_requests', 'user_email')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_log_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_log_action', table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'new_data',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_data',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'vendor_name')
    op.drop_column('audit_logs', 'po_number')
    op.drop_column('audit_logs', 'user_name')
    op.drop_column('audit_logs', 'user_email')
    # NOTE: FK, indexes, and columns below (contact_email, contact_phone,
    # notes, updated_at) on 'appointments' are owned by 126b146b34b0 —
    # not dropped here. The alter_column calls are harmless no-ops.
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'purpose',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('appointments', 'appointment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('appointments', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('appointments', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_table('workflow_items',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requested_by_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('requested_by_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('evidence_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verdict', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_items_pkey'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey')),
    sa.UniqueConstraint('key', name=op.f('system_settings_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('subscription_requests',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_requests_pkey'))
    )
    op.create_table('role_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('role_settings_pkey')),
    sa.UniqueConstraint('role_name', name=op.f('role_settings_role_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # NOTE: 'credibility_review_stages' owned by ec42f3e94788 — not dropped here
    op.drop_index(op.f('ix_sales_invoice_items_invoice_id'), table_name='sales_invoice_items')
    op.drop_index(op.f('ix_sales_invoice_items_id'), table_name='sales_invoice_items')
    op.drop_table('sales_invoice_items')
    op.drop_index(op.f('ix_sales_invoice_audit_logs_timestamp'), table_name='sales_invoice_audit_logs')
    op.drop_index(op.f('ix_sales_invoice_audit_logs_sales_invoice_id'), table_name='sales_invoice_audit_logs')
    op.drop_index(op.f('ix_sales_invoice_audit_logs_performed_by_user_id'), table_name='sales_invoice_audit_logs')
    op.drop_index(op.f('ix_sales_invoice_audit_logs_id'), table_name='sales_invoice_audit_logs')
    op.drop_index(op.f('ix_sales_invoice_audit_logs_action'), table_name='sales_invoice_audit_logs')
    op.drop_table('sales_invoice_audit_logs')
    # NOTE: 'purchase_order_audit_logs' owned by 17220f9ec8d6 — not dropped here
    op.drop_index(op.f('ix_credibility_reviews_submitted_by_user_id'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_status'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_id'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_created_at'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_business_request_id'), table_name='credibility_reviews')
    # NOTE: 'credibility_reviews' owned by ec42f3e94788 — not dropped here
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index('idx_user_settings_user', table_name='user_settings')
    # NOTE: 'user_settings' owned by a1b2c3d4e5f6 — not dropped here
    op.drop_index(op.f('ix_sales_invoices_user_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_status'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_po_number'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_payment_due_date'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_invoice_number'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_invoice_date'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_customer_gstin'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_created_at'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_country'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_company_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_archived'), table_name='sales_invoices')
    op.drop_index('idx_sales_invoice_number', table_name='sales_invoices')
    op.drop_index('idx_sales_invoice_due_date', table_name='sales_invoices')
    op.drop_index('idx_sales_invoice_company_status', table_name='sales_invoices')
    op.drop_table('sales_invoices')
    # NOTE: 'credit_reports' owned by 0ae42e959edb — not dropped here
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_gstin'), table_name='business_profiles')
    # NOTE: 'business_profiles' owned by 0ae42e959edb — not dropped here
    op.drop_index(op.f('ix_company_ratings_to_company_id'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_rating'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_id'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_from_company_id'), table_name='company_ratings')
    op.drop_index(op.f('ix_company_ratings_created_at'), table_name='company_ratings')
    op.drop_index('idx_rating_from_to', table_name='company_ratings')
    # NOTE: 'company_ratings' owned by 17220f9ec8d6 — not dropped here
    op.drop_index(op.f('ix_credibility_config_last_updated_at'), table_name='credibility_config')
    op.drop_index(op.f('ix_credibility_config_id'), table_name='credibility_config')
    op.drop_index(op.f('ix_credibility_config_created_at'), table_name='credibility_config')
    # NOTE: 'credibility_config' owned by 17220f9ec8d6 — not dropped here
    # 'app_settings' is owned by 17220f9ec8d6 — not dropped here, see upgrade() note above
    # ### end Alembic commands ###
