"""extend_rbac_and_subscriptions

Revision ID: 948c15643e27
Revises: 17220f9ec8d6
Create Date: 2026-04-26 16:30:40.498138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '948c15643e27'
down_revision: Union[str, None] = '17220f9ec8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_related_po_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'purchase_orders', ['related_po_id'], ['id'], ondelete='CASCADE')
    op.add_column('subscriptions', sa.Column('payment_proof_url', sa.String(length=500), nullable=True))
    op.add_column('subscriptions', sa.Column('verified_by', sa.String(length=36), nullable=True))
    op.add_column('subscriptions', sa.Column('processed_by', sa.String(length=36), nullable=True))
    op.add_column('subscriptions', sa.Column('approved_by', sa.String(length=36), nullable=True))
    op.alter_column('subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'subscriptions', 'users', ['verified_by'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['processed_by'], ['id'])
    op.add_column('users', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.alter_column('subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('subscriptions', 'approved_by')
    op.drop_column('subscriptions', 'processed_by')
    op.drop_column('subscriptions', 'verified_by')
    op.drop_column('subscriptions', 'payment_proof_url')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_related_po_id_fkey'), 'notifications', 'purchase_orders', ['related_po_id'], ['id'])
    # ### end Alembic commands ###
