"""add invoice model

Revision ID: a1de3ecaea94
Revises: d2bd2ff290ca
Create Date: 2026-01-04 22:13:01.246070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1de3ecaea94'
down_revision: Union[str, None] = 'd2bd2ff290ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=False),
    sa.Column('counterparty_gstin', sa.String(length=15), nullable=True),
    sa.Column('counterparty_pan', sa.String(length=10), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_frequency_days', sa.Integer(), nullable=True),
    sa.Column('reminder_next_at', sa.DateTime(), nullable=True),
    sa.Column('last_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_history', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_counterparty', 'invoices', ['counterparty_gstin', 'counterparty_pan'], unique=False)
    op.create_index('idx_invoice_user_status', 'invoices', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_counterparty_gstin'), 'invoices', ['counterparty_gstin'], unique=False)
    op.create_index(op.f('ix_invoices_counterparty_pan'), 'invoices', ['counterparty_pan'], unique=False)
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_counterparty_pan'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_counterparty_gstin'), table_name='invoices')
    op.drop_index('idx_invoice_user_status', table_name='invoices')
    op.drop_index('idx_invoice_counterparty', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
