"""add profile photo and company logo to business profile

Revision ID: c80537e2d8c0
Revises: 7060e0366f6a
Create Date: 2026-01-04 21:23:34.819824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80537e2d8c0'
down_revision: Union[str, None] = '7060e0366f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('profile_photo_url', sa.String(length=512), nullable=True))
    op.add_column('business_profiles', sa.Column('company_logo_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'company_logo_url')
    op.drop_column('business_profiles', 'profile_photo_url')
    # ### end Alembic commands ###
