"""add defaulter doc links

Revision ID: d2bd2ff290ca
Revises: 3d2565c409c0
Create Date: 2026-01-04 21:56:37.749853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2bd2ff290ca'
down_revision: Union[str, None] = '3d2565c409c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defaulter_cases', sa.Column('ledger_url', sa.String(length=500), nullable=True))
    op.add_column('defaulter_cases', sa.Column('ca_certificate_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defaulter_cases', 'ca_certificate_url')
    op.drop_column('defaulter_cases', 'ledger_url')
    # ### end Alembic commands ###
