"""Add company_id to global_credibility_index

Revision ID: e1c033d71428
Revises: ec42f3e94788
Create Date: 2026-06-08 23:05:43.565675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c033d71428'
down_revision: Union[str, None] = 'ec42f3e94788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_user_edit_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by_email', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_user_edit_requests_created_at'), 'company_user_edit_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_user_edit_requests_entity_id'), 'company_user_edit_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_company_user_edit_requests_entity_type'), 'company_user_edit_requests', ['entity_type'], unique=False)
    op.create_index(op.f('ix_company_user_edit_requests_id'), 'company_user_edit_requests', ['id'], unique=False)
    op.create_index(op.f('ix_company_user_edit_requests_status'), 'company_user_edit_requests', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_action', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_log_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('business_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('legal_notes', sa.Text(), nullable=True),
    sa.Column('analyzed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_requests_created_at'), 'business_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_business_requests_gstin'), 'business_requests', ['gstin'], unique=False)
    op.create_index(op.f('ix_business_requests_id'), 'business_requests', ['id'], unique=False)
    op.create_index(op.f('ix_business_requests_status'), 'business_requests', ['status'], unique=False)
    op.create_index(op.f('ix_business_requests_user_email'), 'business_requests', ['user_email'], unique=False)
    op.create_index(op.f('ix_business_requests_user_id'), 'business_requests', ['user_id'], unique=False)
    op.create_table('support_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('request_details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_requests_created_at'), 'support_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_requests_id'), 'support_requests', ['id'], unique=False)
    op.create_index(op.f('ix_support_requests_request_type'), 'support_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_support_requests_status'), 'support_requests', ['status'], unique=False)
    op.create_index(op.f('ix_support_requests_user_email'), 'support_requests', ['user_email'], unique=False)
    op.create_index(op.f('ix_support_requests_user_id'), 'support_requests', ['user_id'], unique=False)
    op.drop_index(op.f('idx_cms_section_page_order'), table_name='cms_sections')
    op.drop_index(op.f('ix_cms_sections_id'), table_name='cms_sections')
    op.drop_index(op.f('ix_cms_sections_page_id'), table_name='cms_sections')
    op.drop_table('cms_sections')
    op.drop_index(op.f('ix_cms_pages_id'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_is_published'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_slug'), table_name='cms_pages')
    op.drop_table('cms_pages')
    op.create_foreign_key(None, 'credibility_reviews', 'business_requests', ['business_request_id'], ['id'], ondelete='CASCADE')
    op.add_column('global_credibility_index', sa.Column('company_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_global_credibility_index_company_id'), 'global_credibility_index', ['company_id'], unique=True)
    op.create_foreign_key(None, 'global_credibility_index', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('payment_proof_url', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('payment_proof_filename', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_notice_status', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_support_reason', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_support_evidence_url', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_support_evidence_filename', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_support_status', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('legal_notes', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('evidence_url', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('approval_status', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('payment_receipt_url', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('payment_receipt_filename', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_by', sa.String(length=36), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('pending_changes', sa.JSON(), nullable=True))
    op.add_column('purchase_orders', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'users', ['approved_by'], ['id'])
    op.alter_column('sop_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_sop_documents_id'), 'sop_documents', ['id'], unique=False)
    op.create_index(op.f('ix_sop_documents_uploaded_at'), 'sop_documents', ['uploaded_at'], unique=False)
    # Create the 'userrole' Postgres ENUM type before using it below. The
    # original auto-generated migration assumed this type already existed,
    # which only worked on databases where it had been created out-of-band.
    user_role_enum = postgresql.ENUM(
        'USER', 'COMPANY_ADMIN', 'FINANCIAL', 'OPERATION', 'LEGAL', 'MASTER_ADMIN',
        name='userrole'
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=user_role_enum,
               postgresql_using='role::userrole',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'COMPANY_ADMIN', 'FINANCIAL', 'OPERATION', 'LEGAL', 'MASTER_ADMIN', name='userrole'),
               type_=sa.VARCHAR(length=30),
               postgresql_using='role::varchar',
               existing_nullable=True)
    postgresql.ENUM(name='userrole').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_sop_documents_uploaded_at'), table_name='sop_documents')
    op.drop_index(op.f('ix_sop_documents_id'), table_name='sop_documents')
    op.alter_column('sop_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'rejection_reason')
    op.drop_column('purchase_orders', 'pending_changes')
    op.drop_column('purchase_orders', 'approved_at')
    op.drop_column('purchase_orders', 'approved_by')
    op.drop_column('purchase_orders', 'payment_receipt_filename')
    op.drop_column('purchase_orders', 'payment_receipt_url')
    op.drop_column('purchase_orders', 'approval_notes')
    op.drop_column('purchase_orders', 'approval_status')
    op.drop_column('purchase_orders', 'evidence_url')
    op.drop_column('purchase_orders', 'legal_notes')
    op.drop_column('purchase_orders', 'legal_support_status')
    op.drop_column('purchase_orders', 'legal_support_evidence_filename')
    op.drop_column('purchase_orders', 'legal_support_evidence_url')
    op.drop_column('purchase_orders', 'legal_support_reason')
    op.drop_column('purchase_orders', 'legal_notice_status')
    op.drop_column('payments', 'payment_proof_filename')
    op.drop_column('payments', 'payment_proof_url')
    op.drop_constraint(None, 'global_credibility_index', type_='foreignkey')
    op.drop_index(op.f('ix_global_credibility_index_company_id'), table_name='global_credibility_index')
    op.drop_column('global_credibility_index', 'company_id')
    op.drop_constraint(None, 'credibility_reviews', type_='foreignkey')
    op.create_table('cms_pages',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('seo_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cms_pages_pkey'))
    )
    op.create_index(op.f('ix_cms_pages_slug'), 'cms_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_cms_pages_is_published'), 'cms_pages', ['is_published'], unique=False)
    op.create_index(op.f('ix_cms_pages_id'), 'cms_pages', ['id'], unique=False)
    op.create_table('cms_sections',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['cms_pages.id'], name=op.f('cms_sections_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cms_sections_pkey'))
    )
    op.create_index(op.f('ix_cms_sections_page_id'), 'cms_sections', ['page_id'], unique=False)
    op.create_index(op.f('ix_cms_sections_id'), 'cms_sections', ['id'], unique=False)
    op.create_index(op.f('idx_cms_section_page_order'), 'cms_sections', ['page_id', 'order_index'], unique=False)
    op.drop_index(op.f('ix_support_requests_user_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_user_email'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_status'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_request_type'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_created_at'), table_name='support_requests')
    op.drop_table('support_requests')
    op.drop_index(op.f('ix_business_requests_user_id'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_user_email'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_status'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_id'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_gstin'), table_name='business_requests')
    op.drop_index(op.f('ix_business_requests_created_at'), table_name='business_requests')
    op.drop_table('business_requests')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_log_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_log_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_company_user_edit_requests_status'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_id'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_entity_type'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_entity_id'), table_name='company_user_edit_requests')
    op.drop_index(op.f('ix_company_user_edit_requests_created_at'), table_name='company_user_edit_requests')
    op.drop_table('company_user_edit_requests')
    # ### end Alembic commands ###
