"""Add Global Credibility Index tables

Revision ID: ec42f3e94788
Revises: 948c15643e27
Create Date: 2026-06-03 20:21:19.115723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec42f3e94788'
down_revision: Union[str, None] = '948c15643e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credibility_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_request_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_registration_no', sa.String(length=50), nullable=True),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING_FINANCIAL', 'PENDING_LEGAL', 'PENDING_OPERATIONS', 'PENDING_MASTER_ADMIN', 'APPROVED', 'REJECTED_FINAL', 'REJECTED_FINANCIAL', 'REJECTED_LEGAL', 'REJECTED_OPERATIONS', name='credibilityreviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
)
    op.create_index(op.f('ix_credibility_reviews_business_request_id'), 'credibility_reviews', ['business_request_id'], unique=False)
    op.create_index(op.f('ix_credibility_reviews_created_at'), 'credibility_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_credibility_reviews_id'), 'credibility_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_credibility_reviews_status'), 'credibility_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_credibility_reviews_submitted_by_user_id'), 'credibility_reviews', ['submitted_by_user_id'], unique=False)
    op.create_table('credibility_review_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credibility_review_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('FINANCIAL', 'LEGAL', 'OPERATIONS', 'MASTER_ADMIN', name='credibilityreviewstage'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='reviewdecision'), nullable=True),
    sa.Column('financial_health_score', sa.Integer(), nullable=True),
    sa.Column('payment_history', sa.Enum('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', name='paymenthistory'), nullable=True),
    sa.Column('financial_risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='financialrisklevel'), nullable=True),
    sa.Column('legal_status', sa.Enum('CLEAN', 'MINOR_DISPUTES', 'ACTIVE_LITIGATION', 'BLACKLISTED', name='legalstatus'), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('court_cases', sa.Integer(), nullable=True),
    sa.Column('operational_reliability', sa.Enum('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', name='operationalreliability'), nullable=True),
    sa.Column('dispute_history', sa.Enum('NONE', 'MINOR', 'MAJOR', name='disputehistory'), nullable=True),
    sa.Column('partner_trust_score', sa.Float(), nullable=True),
    sa.Column('ai_credit_risk_verdict', sa.Enum('LOW_RISK', 'MEDIUM_RISK', 'HIGH_RISK', 'NOT_RATED', name='aicreditriskverdict'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credibility_review_id'], ['credibility_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credibility_review_stages_credibility_review_id'), 'credibility_review_stages', ['credibility_review_id'], unique=False)
    op.create_index(op.f('ix_credibility_review_stages_id'), 'credibility_review_stages', ['id'], unique=False)
    op.create_index(op.f('ix_credibility_review_stages_reviewed_by_user_id'), 'credibility_review_stages', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_credibility_review_stages_stage'), 'credibility_review_stages', ['stage'], unique=False)
    op.create_table('global_credibility_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_registration_no', sa.String(length=50), nullable=True),
    sa.Column('partner_trust_score', sa.Float(), nullable=False),
    sa.Column('ai_credit_risk_verdict', sa.Enum('LOW_RISK', 'MEDIUM_RISK', 'HIGH_RISK', 'NOT_RATED', name='aicreditriskverdict'), nullable=True),
    sa.Column('credibility_status', sa.Enum('CREDIBILITY_VERIFIED', 'STANDARD', name='credibilitystatus'), nullable=True),
    sa.Column('financial_health_score', sa.Integer(), nullable=True),
    sa.Column('legal_status', sa.Enum('CLEAN', 'MINOR_DISPUTES', 'ACTIVE_LITIGATION', 'BLACKLISTED', name='legalstatus'), nullable=True),
    sa.Column('operational_reliability', sa.Enum('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', name='operationalreliability'), nullable=True),
    sa.Column('approved_by_master_admin_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('credibility_review_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_master_admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credibility_review_id'], ['credibility_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_credibility_index_approved_by_master_admin_id'), 'global_credibility_index', ['approved_by_master_admin_id'], unique=False)
    op.create_index(op.f('ix_global_credibility_index_company_name'), 'global_credibility_index', ['company_name'], unique=False)
    op.create_index(op.f('ix_global_credibility_index_company_registration_no'), 'global_credibility_index', ['company_registration_no'], unique=False)
    op.create_index(op.f('ix_global_credibility_index_created_at'), 'global_credibility_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_global_credibility_index_credibility_review_id'), 'global_credibility_index', ['credibility_review_id'], unique=False)
    op.create_index(op.f('ix_global_credibility_index_id'), 'global_credibility_index', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_credibility_index_id'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_credibility_review_id'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_created_at'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_company_registration_no'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_company_name'), table_name='global_credibility_index')
    op.drop_index(op.f('ix_global_credibility_index_approved_by_master_admin_id'), table_name='global_credibility_index')
    op.drop_table('global_credibility_index')
    op.drop_index(op.f('ix_credibility_review_stages_stage'), table_name='credibility_review_stages')
    op.drop_index(op.f('ix_credibility_review_stages_reviewed_by_user_id'), table_name='credibility_review_stages')
    op.drop_index(op.f('ix_credibility_review_stages_id'), table_name='credibility_review_stages')
    op.drop_index(op.f('ix_credibility_review_stages_credibility_review_id'), table_name='credibility_review_stages')
    op.drop_table('credibility_review_stages')
    op.drop_index(op.f('ix_credibility_reviews_submitted_by_user_id'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_status'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_id'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_created_at'), table_name='credibility_reviews')
    op.drop_index(op.f('ix_credibility_reviews_business_request_id'), table_name='credibility_reviews')
    op.drop_table('credibility_reviews')
    # ### end Alembic commands ###
