"""add_cms_tables

Revision ID: f5g6h7i8j9k0
Revises: e4f5g6h7i8j9
Create Date: 2026-01-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'f5g6h7i8j9k0'
down_revision = 'e4f5g6h7i8j9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table exists before creating
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'cms_pages' not in tables:
        op.create_table('cms_pages',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=True),
        sa.Column('seo_title', sa.String(length=255), nullable=True),
        sa.Column('seo_description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_cms_pages_id'), 'cms_pages', ['id'], unique=False)
        op.create_index(op.f('ix_cms_pages_slug'), 'cms_pages', ['slug'], unique=True)
        op.create_index(op.f('ix_cms_pages_is_published'), 'cms_pages', ['is_published'], unique=False)

    if 'cms_sections' not in tables:
        op.create_table('cms_sections',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('page_id', sa.String(length=36), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('is_visible', sa.Boolean(), nullable=True),
        sa.Column('content', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['page_id'], ['cms_pages.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_cms_sections_id'), 'cms_sections', ['id'], unique=False)
        op.create_index(op.f('ix_cms_sections_page_id'), 'cms_sections', ['page_id'], unique=False)
        op.create_index('idx_cms_section_page_order', 'cms_sections', ['page_id', 'order_index'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cms_section_page_order', table_name='cms_sections')
    op.drop_index(op.f('ix_cms_sections_page_id'), table_name='cms_sections')
    op.drop_index(op.f('ix_cms_sections_id'), table_name='cms_sections')
    op.drop_table('cms_sections')
    op.drop_index(op.f('ix_cms_pages_is_published'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_slug'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_id'), table_name='cms_pages')
    op.drop_table('cms_pages')
    # ### end Alembic commands ###
